
- name: Create Linux user with sudo/wheel and SSH key
  hosts: all
  become: true
  vars:
    username: test
    ssh_public_key: "ssh-rsa 123 user"

  tasks:
    - name: Ensure the user exists
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        create_home: yes

    - name: Determine sudo group based on OS family
      ansible.builtin.set_fact:
        sudo_group: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"

    - name: Add user to appropriate sudo/wheel group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: "{{ sudo_group }}"
        append: yes

    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Add SSH public key
      ansible.builtin.copy:
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        content: "{{ ssh_public_key }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'
